config/routes.rb
Rails.application.routes.draw do
  get 'sort/sort'
  get 'search/get'
  get 'search/search'
  delete 'favourites/del', to: 'favourites#del'
  resources :favourites

  get 'users/profile'
  resources :reviews
  resources :authors
  resources :categories
  resources :mangas
  devise_for :users
  get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :mangas
    
    has_one_attached :author_image
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :mangas
end

app/models/favourite.rb
class Favourite < ApplicationRecord
    belongs_to :user
    belongs_to :manga
end

app/models/manga.rb
class Manga < ApplicationRecord
    belongs_to :author
    has_many :reviews
	has_many :favourites
    belongs_to :category
    # has_and_belongs_to_many :users, join_table: 'favourites'
    
    has_one_attached :image

    def get_author
		if self.author
			self.author.name
		else
			"Deleted"
		end
    end
    
    def get_category
		if self.category
			self.category.category
		else
			"Deleted"
		end
    end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :manga
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  #validates :name, presence: true
  #validates :birthday, presence: true
  #validates :gender, presence: true
  #validates :phone, presence: true
  #validates :location, presence: true
  #validates :about, presence: true
  
  has_one_attached :avatar
  
  has_many :reviews
  # has_and_belongs_to_many :mangas, join_table: 'favourites'
  has_many :favourites
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_favourite, only: %i[ show edit update destroy ]

  # GET /favourites or /favourites.json
  def index  
    if user_signed_in?
      @favourites = Favourite.where(user_id: current_user.id)
    else
      @favourites = []
    end
  end

  # GET /favourites/1 or /favourites/1.json
  def show
    
  end

  # GET /favourites/new
  def new
    @favourite = Favourite.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # POST /favourites or /favourites.json
  def create
    @favourite = Favourite.new(favourite_params)

    respond_to do |format|
      if @favourite.save
        url = '/mangas/'+ @favourite.manga_id.to_s
        format.html { redirect_to url, notice: "Favourite was successfully created." }
        format.json { render :show, status: :created, location: @favourite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites/1 or /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to @favourite, notice: "Favourite was successfully updated." }
        format.json { render :show, status: :ok, location: @favourite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1 or /favourites/1.json
  def destroy
    @favourite.destroy
    respond_to do |format|
      format.html { redirect_to favourites_url, notice: "Favourite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # DELETE /favourites/del?user_id=1&manga_id=1
  def del
    Favourite.delete_by(user_id: params[:user_id], manga_id: params[:manga_id])
    url = '/mangas/'+ params[:manga_id].to_s
    respond_to do |format|
      format.html { redirect_to url, notice: "Favourite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favourite_params
      params.require(:favourite).permit(:user_id, :manga_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: %i[ show edit update destroy ]

  # GET /mangas or /mangas.json
  def index
    @mangas = Manga.all
  end

  # GET /mangas/1 or /mangas/1.json
  def show
    @review = Review.new

    @favourites = Favourite.new
    @is_active = false;
    if user_signed_in?
        @is_active = Favourite.exists?(user_id: current_user.id, manga_id: params[:id]) 
    end
  end

  # GET /mangas/new
  def new
    @manga = Manga.new
  end

  # GET /mangas/1/edit
  def edit
  end

  # POST /mangas or /mangas.json
  def create
    @manga = Manga.new(manga_params)

    respond_to do |format|
      if @manga.save
        format.html { redirect_to @manga, notice: "Manga was successfully created." }
        format.json { render :show, status: :created, location: @manga }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangas/1 or /mangas/1.json
  def update
    respond_to do |format|
      if @manga.update(manga_params)
        format.html { redirect_to @manga, notice: "Manga was successfully updated." }
        format.json { render :show, status: :ok, location: @manga }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangas/1 or /mangas/1.json
  def destroy
    @manga.destroy
    respond_to do |format|
      format.html { redirect_to mangas_url, notice: "Manga was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manga
      @manga = Manga.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manga_params
      params.require(:manga).permit(:title, :category_id, :author_id, :description, :image)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def get
      
  end

  def search
      @mangas = Manga.where("title LIKE ?", "%"  + params[:keyword] + "%")
  end
end

app/controllers/sort_controller.rb
class SortController < ApplicationController
  def sort
      @mangas = Manga.all.order(title: :asc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sort_helper.rb
module SortHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favourites/_form.html.erb
<%= form_with(model: favourite, local: true) do |form| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
        <% favourite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :manga_id %>
    <%= form.number_field :manga_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<h1>Recent favourites</h1>
<% if @favourites.count > 0 %>
<table class="table">
  <thead class="table-dark fs-5">
    <tr>
      <th>User</th>
      <th>Manga</th>
      <th>Time</th>
    </tr>
  </thead>

  <tbody>
    <% @favourites.each do |favourite| %>
      <tr>
        <% if favourite.user.name != "" %>
	  <td><%= link_to favourite.user.name, "#", class: "btn btn-outline-primary" %> </td>
        <% else %>
	  <td><%= link_to favourite.user.email, "#", class: "btn btn-outline-primary" %> </td>
        <% end %>
        <% if favourite.manga %>       
          <td><%= link_to favourite.manga.title, favourite.manga, class: "btn btn-outline-dark" %> </td>
        <% else %>
          <td><%= link_to "Deleted", "#", class: "btn btn-outline-dark" %> </td>
        <% end %>
        <td><%= link_to favourite.created_at.localtime.strftime("%d/%m/%Y %H:%M:%S"), "#", class: "btn btn-outline-dark" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p class="fs-4">No favourite</p>
<% end %>

app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favourite.user_id %>
</p>

<p>
  <strong>Manga:</strong>
  <%= @favourite.manga_id %>
</p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>