config/routes.rb
Rails.application.routes.draw do
  get 'sort/sort'
  get 'search/get'
  get 'search/search'
  delete 'favourites/del', to: 'favourites#del'
  resources :favourites

  get 'users/profile'
  resources :reviews
  resources :authors
  resources :categories
  resources :mangas
  devise_for :users
  get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :mangas
    
    has_one_attached :author_image
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :mangas
end

app/models/favourite.rb
class Favourite < ApplicationRecord
    belongs_to :user
    belongs_to :manga
end

app/models/manga.rb
class Manga < ApplicationRecord
    belongs_to :author
    has_many :reviews
	has_many :favourites
    belongs_to :category
    # has_and_belongs_to_many :users, join_table: 'favourites'
    
    has_one_attached :image

    def get_author
		if self.author
			self.author.name
		else
			"Deleted"
		end
    end
    
    def get_category
		if self.category
			self.category.category
		else
			"Deleted"
		end
    end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :manga
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  #validates :name, presence: true
  #validates :birthday, presence: true
  #validates :gender, presence: true
  #validates :phone, presence: true
  #validates :location, presence: true
  #validates :about, presence: true
  
  has_one_attached :avatar
  
  has_many :reviews
  # has_and_belongs_to_many :mangas, join_table: 'favourites'
  has_many :favourites
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: %i[ show edit update destroy ]

  # GET /mangas or /mangas.json
  def index
    @mangas = Manga.all
  end

  # GET /mangas/1 or /mangas/1.json
  def show
    @review = Review.new

    @favourites = Favourite.new
    @is_active = false;
    if user_signed_in?
        @is_active = Favourite.exists?(user_id: current_user.id, manga_id: params[:id]) 
    end
  end

  # GET /mangas/new
  def new
    @manga = Manga.new
  end

  # GET /mangas/1/edit
  def edit
  end

  # POST /mangas or /mangas.json
  def create
    @manga = Manga.new(manga_params)

    respond_to do |format|
      if @manga.save
        format.html { redirect_to @manga, notice: "Manga was successfully created." }
        format.json { render :show, status: :created, location: @manga }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangas/1 or /mangas/1.json
  def update
    respond_to do |format|
      if @manga.update(manga_params)
        format.html { redirect_to @manga, notice: "Manga was successfully updated." }
        format.json { render :show, status: :ok, location: @manga }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangas/1 or /mangas/1.json
  def destroy
    @manga.destroy
    respond_to do |format|
      format.html { redirect_to mangas_url, notice: "Manga was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manga
      @manga = Manga.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manga_params
      params.require(:manga).permit(:title, :category_id, :author_id, :description, :image)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def get
      
  end

  def search
      @mangas = Manga.where("title LIKE ?", "%"  + params[:keyword] + "%")
  end
end

app/controllers/sort_controller.rb
class SortController < ApplicationController
  def sort
      @mangas = Manga.all.order(title: :asc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sort_helper.rb
module SortHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'マンガー世界', root_path, class:"navbar-brand fs-3"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item fs-5">
          <%= link_to '私たち', home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
            <li class="nav-item fs-5">
              <%= link_to 'マンガー', mangas_path, class:"nav-link" %>
            </li>
            <li class="nav-item fs-5">
              <%= link_to '著者', authors_path, class:"nav-link" %>
            </li>
            <li class="nav-item fs-5">
              <%= link_to '種類', categories_path, class:"nav-link" %>
            </li>
            <li class="nav-item fs-5">
              <%= link_to '最近のレビュー', reviews_path, class:"nav-link" %>
            </li>
            <li class="nav-item btn-group">
              <button type="button" class="btn btn-outline-secondary dropdown-toggle fs-5" data-bs-toggle="dropdown" aria-expanded="false"> 
                <% if current_user.name != "" %>
                  <%= current_user.name %>
                <% else %>
                  <%= current_user.email %>
                <% end %>
              </button>
              <ul class="dropdown-menu dropdown-menu-dark fs-5" aria-labelledby="dropdownMenuClickableInside">
                <li><%= link_to '情報', users_profile_path, class:"dropdown-item" %></li>
                <li><%= link_to '情報整理', edit_user_registration_path, class:"dropdown-item" %></li>
                <li><%= link_to '趣味', favourites_path, class:"dropdown-item" %></li>
                <li><%= link_to 'サインアウト', destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
              </ul>
            </li>
        <% else %>
            <li class="nav-item fs-5">
              <%= link_to 'ログイン', new_user_session_path, class:"nav-link" %>
            </li>
            <li class="nav-item fs-5">
              <%= link_to 'サインアップ', new_user_registration_path, class:"nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container-fluid p-5  text-white text-center" style="background: pink">
  <!-- <h1>Team wibu</h1> -->
  <h2>マンガー　レビュー</h2> 
</div>
<div class="mx-auto" style="width: 300px;">

<h2 style="text-align: center">　チームメンバー </h2>
</div>

<div class="d-flex  mt-5" style="flex-direction: column; text-align:center">
    <div class="">
            <div class="col-sm-3" style="display:inline-block; width: 400px">
                <h3>Nguyen Dinh Xuan Nghiem</h3>
                <p>20194637</p>
            </div>
            <div class="col-sm-3" style="display:inline-block">
                <h3>Ngo Minh Quan</h3>
                <p> 20194652</p>
            </div>
            <div class="col-sm-3" style="display:inline-block">
                <h3>Ta Huy Tuan Te</h3>        
                <p>20194708</p>
            </div>
    </div>
    <div class="" style="padding-top: 50px">
            <div class="col-sm-2"  style="display:inline-block">
                <h3>Le Van Nam</h3>        
                <p>20194627</p>
            </div>
            <div class="col-sm-2" style="display:inline-block; width: 300px">
                <h3>Pham Thanh Nam</h3>        
                <p>20194630</p>
            </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid p-5  text-white text-center" style="background: pink">
  <h1 style="margin-bottom: 10px">トュアンと友達</h1>
  <h2>マンガーレビュー</h2> 
</div>
  

app/views/search/get.html.erb
<h1>Search#get</h1>
<p>Find me in app/views/search/get.html.erb</p>

app/views/search/search.html.erb
<!-- <h1>Search#search</h1>
<p>Find me in app/views/search/search.html.erb</p> -->

<table class="table">
  <thead class="table-dark fs-5">
    <tr>
      <th>タイトル</th>
      <th>種類</th>
      <th>著者</th>
      <th>説明</th>
    </tr>
  </thead>

  <tbody>
    <% @mangas.each_with_index do |manga| %>
      <tr>
        <td><%= link_to manga.title, manga, class: "btn btn-outline-primary text-break" %> </td>
        <td><%= link_to manga.get_category, manga.category, class: "btn btn-outline-dark" %> </td>
        <td><%= link_to manga.get_author, manga.author, class: "btn btn-outline-dark " %> </td>
        <% if manga.description != "" %>
          <td><%= link_to manga.description, "#", class: "btn btn-outline-dark text-break text-start" %> </td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sort/sort.html.erb
<!-- <h1>Sort#sort</h1>
<p>Find me in app/views/sort/sort.html.erb</p> -->

<!-- <h1>Result table</h1> -->
<table class="table">
  <thead class="table-dark fs-5">
    <tr>
      <th>タイトル</th>
      <th>種類</th>
      <th>著者</th>
      <th>説明</th>
    </tr>
  </thead>

  <tbody>
    <% @mangas.each_with_index do |manga| %>
      <tr>
        <td><%= link_to manga.title, manga, class: "btn btn-outline-primary text-break" %> </td>
        <td><%= link_to manga.get_category, manga.category, class: "btn btn-outline-dark" %> </td>
        <td><%= link_to manga.get_author, manga.author, class: "btn btn-outline-dark " %> </td>
        <% if manga.description != "" %>
          <td><%= link_to manga.description, "#", class: "btn btn-outline-dark text-break text-start" %> </td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>